#!/bin/env/bash

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        echo "Hello World!";
    }
}
EOF

# Restart Nginx
sudo service nginx restart
