#!/usr/bin/env bash
# A Bash script that configures a server by restoring the default server port
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
