#!/usr/bin/env bash

server {
    listen 80;
    server_name localhost http://102.216.154.20;  # Replace "your_public_ip" with your actual public IP

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;  # Proxy to process on port 5000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:5000;  # Default proxy location
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

